### ISSUE TITLE
indentation not working

### ISSUE THREAD

**Issue by sveeig** [lepture/vim-velocity#3]
The only thing that works is indentation of HTML in my .vm files. But indentation of nested control statements does not work. For example, I have something like:

``` velocity
#if ( true == true )
    #if ( false == false )
        <div>Hello</div>
    #else
        <div>Bye</div>
    #end
#end
```

If I now run vim's equals-indentation over it (e.g. select as visual block, press '='), it ends up like this:

``` velocity
#if ( true == true )
#if ( false == false )
<div>Hello</div>
#else
<div>Bye</div>
#end
#end
```

ps: I installed this via git clone and pathogen.

**Comment by lepture** [comment]
I removed the indention script. It didn't work well as I expected.

**Comment by sveeig** [comment]
ah, makes sense then :-) I'll just close here because it's a non-issue then. An updated README would be nice though.

**Comment by shepherdwind** [comment]
@rompetroll The indention file in my folk is ok. If you need this feature, you can try [this](https://github.com/shepherdwind/vim-velocity).
